# Generated by Django 5.1.5 on 2025-08-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20250827_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='negative_marks',
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1.0, editable=False),
        ),
    ]
