# Generated by Django 5.1.5 on 2025-08-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, help_text='For MCQ: enter A, B, C, or D; For True/False: enter True or False; For Numeric: enter the number as text.', max_length=50, null=True),
        ),
    ]
