# Generated by Django 3.2.12 on 2025-12-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.test'),
        ),
    ]
